routes/web.php
<?php

Route::get('/', function() {
	return view('soon');
});

// Route::get('/', 'PageController@newhome')->name('new_home');
// Route::get('/old', 'PageController@home')->name('home');
// Route::get('/new', 'PageController@newestHome')->name('newest_home');
// Route::get('/menu/{active?}', 'PageController@menu')->name('menu');
// Route::get('/location', 'PageController@location')->name('location');

// /* Deals */
// Route::group(['prefix' => 'deal'], function() {
// 	Route::get('/{deal}', 'PageController@deal');
// });

// /* Categories */
// Route::group(['prefix' => 'categories'], function() {
// 	Route::get('/{category?}', 'CategoryController@all')->name('categories');
// });

// /* Products */
// Route::group(['prefix' => 'products'], function() {
// 	Route::get('/{product}', 'ProductController@single')->name('product');
// });

// /* Cart */
// Route::group(['prefix' => 'cart'], function() {
// 	Route::get('/', 'CartController@my')->name('cart');
// 	Route::get('/remove/{item}', 'CartController@remove')->name('cart_remove');
// });

// /* Account */
// Route::group(['prefix' => 'account', 'middleware' => 'auth'], function() {
// 	Route::get('/', 'AccountController@home')->name('account_home');
// 	Route::get('/orders', 'AccountController@orders')->name('account_orders');
// 	Route::get('/addresses', 'AccountController@addresses')->name('account_addresses');
// 	Route::get('/payments', 'AccountController@payments')->name('account_payments');
// });

// /* Orders */
// Route::get('/orders/{order}', 'AccountController@order')->name('order');
// Route::get('/ordersnew/{order}', 'PageController@order');

// /* Auth */
// Route::group(['prefix' => 'auth'], function() {
// 	Route::post('/login', 'AuthController@login');
// 	Route::get('/logout', 'AuthController@logout')->name('logout');
// });

// /* Admin */
// Route::get('/login', 'AdminController@login')->name('admin_login');
// Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
// 	Route::get('/', 'AdminController@dashboard')->name('admin_dashboard');

// 	// Products
// 	Route::group(['prefix' => 'products'], function() {
// 		Route::get('/', 'AdminController@products')->name('admin_products');
// 		Route::get('/new', 'AdminController@newProduct')->name('admin_product_new');

// 		Route::get('/categories', 'AdminController@categories')->name('admin_product_categories');
// 		Route::get('/categories/new', 'AdminController@newCategory')->name('admin_product_categories_new');
// 		Route::get('/categories/{category}', 'AdminController@editCategory')->name('admin_product_categories_edit');

// 		Route::get('/sauces', 'AdminController@sauces')->name('admin_product_sauces');
// 		Route::get('/sauces/new', 'AdminController@newSauce')->name('admin_product_sauces_new');
// 		Route::get('/sauces/{sauce}', 'AdminController@editSauce')->name('admin_product_sauces_edit');
// 		Route::get('/fillings', 'AdminController@fillings')->name('admin_product_fillings');
// 		Route::get('/fillings/new', 'AdminController@newFilling')->name('admin_product_fillings_new');
// 		Route::get('/fillings/{filling}', 'AdminController@editFilling')->name('admin_product_fillings_edit');

// 		Route::get('/{product}', 'AdminController@editProduct')->name('admin_product');

// 		Route::post('/new', 'AdminController@doNew');
// 		Route::post('/categories/new', 'AdminController@doNewCategory');
// 		Route::post('/categories/{category}', 'AdminController@doEditCategory');
// 		Route::post('/sauces/new', 'AdminController@doNewSauce');
// 		Route::post('/sauces/{sauce}', 'AdminController@doEditSauce');
// 		Route::post('/fillings/new', 'AdminController@doNewFilling');
// 		Route::post('/fillings/{filling}', 'AdminController@doEditFilling');
// 		Route::post('/{product}', 'AdminController@doEdit');
// 	});

// 	// Orders
// 	Route::group(['prefix' => 'orders'], function() {
// 		Route::get('/', 'AdminController@orders')->name('admin_orders');
// 	});

// 	// Pages
// 	Route::group(['prefix' => 'pages'], function() {
// 		Route::get('/', 'AdminController@pages')->name('admin_pages');
// 	});

// 	// Users
// 	Route::group(['prefix' => 'users'], function() {
// 		Route::get('/', 'AdminController@users')->name('admin_users');
// 	});
// });

// /* Page catch all */
// Route::get('/{page}', 'PageController@generic')->name('generic');

app/Models/CartItem.php
<?php

namespace App\Models;
use App\Models\ProductFilling;
use App\Models\ProductSauce;
use Illuminate\Database\Eloquent\Model;

class CartItem extends Model {
    protected $table = 'cart_items',
              $fillable = ['cart_id', 'product_id', 'fillings', 'sauces', 'cheese', 'quantity'],
              $appends = ['actual_fillings', 'actual_sauces', 'filling_list', 'sauce_list', 'price'];

    public function getPriceAttribute()
    {
        $price = 0;

        if($this->product) $price = number_format(($this->product->price * $this->quantity), 2);
        if($this->deal) $price = number_format(($this->deal->price * $this->quantity), 2);
        
        return $price;
    }

    public function getDealOptionsAttribute($value)
    {
        if(!$value) return null;

        $options = json_decode($value);

        foreach($options as &$option) {
            $fillings = [];
            $sauces = [];

            if($option->fillings) {
                foreach($option->fillings as $filling) {
                    $fillings[] = ProductFilling::find($filling);
                }
            }

            if($option->sauces) {
                foreach($option->sauces as $sauce) {
                    $sauces[] = ProductSauce::find($sauce);
                }
            }

            $option->fillings = $fillings;
            $option->sauces = $sauces;
        }

        return $options;
    }

    public function getActualFillingsAttribute()
    {
        if(!$this->fillings) return null;

    	$end_fillings = [];
    	$fillings = json_decode($this->fillings);

    	foreach($fillings as $filling) {
    		$end_fillings[] = ProductFilling::find($filling);
        }

    	return $end_fillings;
    }

    public function getActualSaucesAttribute()
    {
        if(!$this->sauces) return null;

    	$end_sauces = [];
    	$sauces = json_decode($this->sauces);

    	foreach($sauces as $sauce) {
    		$end_sauces[] = ProductSauce::find($sauce);
    	}

    	return $end_sauces;
    }

    public function getFillingListAttribute()
    {
        if(!$this->actual_fillings) return null;

        $list = '';
        foreach($this->actual_fillings as $filling) {
            $list .= $filling->name . ', ';
        }
        
        return substr($list, 0, -2);
    }

    public function getSauceListAttribute()
    {
        if(!$this->actual_sauces) return null;

        $list = '';
        foreach($this->actual_sauces as $sauce) {
            $list .= $sauce->name . ', ';
        }
        
        return substr($list, 0, -2);
    }

    public function product()
    {
        return $this->hasOne(\App\Models\Product::class, 'id', 'product_id');
    }

    public function deal()
    {
        return $this->hasOne(\App\Models\Deal::class, 'id', 'deal_id');
    }
}

resources/views/cart.blade.php
@extends('generic.layout')

@section('content')
	<div class="page page-cart">
		<div class="hero">
			<div class="caption">
				<h2>Your Cart</h2>
				<h3>Sit amet, consectetur adipiscing elit</h3>
			</div>
		</div>

		<div class="cart">
			<div class="container">
				@if($cart->total_items > 0)
					<div class="cart-contents">
						@foreach($cart->items as $item)
							<div class="cart-item">
								<div class="image">
									<img src="{{ $item->product->image_thumbnail }}" class="img-fluid" />
								</div>
								<div class="info">
									<h2>{{ $item->quantity }} x {{ $item->product->name }} @if($item->cheese)<span class="badge">with cheese</span>@endif</h2>
									<p><strong>Fillings:</strong> @if($item->filling_list){{ $item->filling_list }}@else None @endif</p>
									<p><strong>Sauces:</strong> @if($item->sauce_list){{ $item->sauce_list }}@else None @endif</p>
								</div>
								<div class="price">
									<h3>&pound;{{ $item->price }}</h3>
									<a href="{{ route('cart_remove', ['item' => $item->id]) }}">Remove</a>
								</div>
							</div>
						@endforeach

						<div class="cart-total">
							<h2 class="right">Total cart cost <span>&pound;{{ $cart->total_price }}</span></h2>
						</div>
					</div>
					<div class="payment">
						@if(Auth::user())
							<payment-user></payment-user>
						@else
							<payment-guest></payment-guest>
						@endif
					</div>
				@else
					<div class="empty-cart">
						<span class="fa fa-shopping-basket"></span>
						<h2>Your cart is empty</h2>
						<p>You have no items in your cart, use the button below to browse through our selection of food and drinks</p>
						<a href="{{ route('categories') }}" class="btn btn-primary">Browse Menu</a>
					</div>
				@endif
			</div>
		</div>
	</div>
@endsection

resources/views/categories.blade.php
@extends('generic.layout')

@section('content')
	<div class="page page-categories">
		<div class="tabs">
			<div class="container">
				<ul>
					@foreach($categories as $cat)
						<li @if($category->slug == $cat->slug) class="active"@endif><a href="{{ route('categories', $cat->slug) }}">{{ $cat->name }}</a></li>
					@endforeach
				</ul>
			</div>
		</div>
		<div class="products">
			<div class="container">
				<div class="row">
					@foreach($category->products as $product)
						<div class="col-md-6">
							<div class="product">
								<div class="image" style="background: url({{ $product->image }}) no-repeat center center; background-size: cover;"></div>
								<div class="info">
									<h2>{{ $product->name }} <small class="float-right">&pound;{{ $product->price }}</small></h2>
									<h3>{{ $product->tagline }}</h3>
									<p>{{ $product->description }}</p>
								</div>
								<div class="row actions">
									<div class="col-md-6">
										<button-add-to-cart product_id="{{ $product->id }}"></button-add-to-cart>
									</div>
									<div class="col-md-6">
										<p>Select your options when you add to cart</p>
									</div>
								</div>
							</div>
						</div>
					@endforeach
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/category.blade.php
@extends('generic.layout')

@section('content')
	<div class="page page-category">
		<div
			class="hero"
			style="background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4)), url('{{ $category->image }}') no-repeat center center; background-attachment: fixed; background-size: cover;"
		>
			<div class="caption">
				<h2>{{ $category->name }}</h2>
				<h3>Sit amet, consectetur adipiscing elit</h3>
			</div>
		</div>

		<div class="products">
			<div class="container">
				<div class="row">
					@foreach($category->products as $product)
						<div class="col-md-4">
							<div class="product">
								<a href="{{ route('product', ['product' => $product->slug]) }}"><img src="{{ $product->image }}" class="img-fluid" /></a>
								<div class="info">
									<h2><a href="{{ route('product', ['product' => $product->slug]) }}">{{ $product->name }}</a></h2>
									<p>{{ $product->description }}</p>
									<a href="{{ route('product', ['product' => $product->slug]) }}" class="btn btn-primary">View product</a>
								</div>
							</div>
						</div>
					@endforeach
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/deal.blade.php
@extends('generic.newlayout')

@section('header')
	@include('generic.newheader')
@endsection

@section('content')
	<div class="page page-deal">
		<smart-deal></smart-deal>
	</div>

	<modal-product action="deal"></modal-product>
	<smart-cart minimized="true"></smart-cart>
@endsection

@section('footer')
	@include('generic.footer')
@endsection

@section('scripts')
	<script type="text/javascript">
		var _categories = {!! $categories !!};
		var _deal = {!! $deal !!};
		var _sauces = {!! $sauces !!};
		var _fillings = {!! $fillings !!};
	</script>
@endsection

resources/views/generic.blade.php
@extends('generic.layout')

@section('content')
	<div class="page page-generic">
		<div class="hero">
			<div class="caption">
				<h2>{{ $page->name }}</h2>
				<h3>{{ $page->subtitle }}</h3>
			</div>
		</div>

		<div class="page-content">
			<div class="container">
				<h2>The meal deal <small class="float-right">Hello, world</small></h2>
			</div>
		</div>
	</div>
@endsection

resources/views/home.blade.php
@extends('generic.layout')

@section('content')
	<div class="page page-home">
		<div class="hero">
			<div class="caption">
				<img src="/images/logo-loop.gif" class="logo animated fadeIn" />
				<!-- <div class="logo-animation-sprite" id="restart-animation"></div> -->
				<a href="{{ route('categories') }}" class="btn btn-default">Browse our menu</a>
			</div>
		</div>

		<div class="blocks">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<div class="block block-one">
							<a href="{{ route('categories', 'deals') }}">
								<img src="/images/banners/mealdeal.jpg" class="img-fluid" />
							</a>
						</div>
						<div class="block block-one">
							<a href="{{ route('location') }}">
								<img src="/images/banners/delivery.jpg" class="img-fluid" />
							</a>
						</div>
					</div>
					<div class="col-md-8">
						<div class="block block-two">
							<img src="/images/banners/deliverycharge.jpg" class="img-fluid" />
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="featured-product">
			<div class="container">
				<div class="row">
					<div class="col-md-7">
						<h2>Try our brand new</h2>
						<h3>Jerk Chicken</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae elit ac lacus facilisis accumsan. Proin et tellus auctor, dignissim libero ut, mattis enim. Donec mollis nulla imperdiet mauris lobortis posuere.</p>
						<a href="{{ route('product', ['product' => 'jerk-chicken']) }}" class="btn btn-default">Read more</a>
					</div>
					<div class="col-md-5">
						<img src="/images/products/bagel1.webp" />
					</div>
				</div>
			</div>
		</div>

		<div class="products">
			<div class="container">
				<div class="row">
					@foreach($categories as $category)
						<div class="col-md-3">
							<div class="product">
								<a href="{{ route('categories', $category->slug) }}"><img src="{{ $category->image }}" class="img-fluid" /></a>
								<div class="info">
									<h2><a href="{{ route('categories', $category->slug) }}">{{ $category->name }}</a></h2>
									<p>{{ Str::limit($category->description, 50) }}</p>
									<a href="{{ route('categories', $category->slug) }}" class="btn btn-primary">Browse</a>
								</div>
							</div>
						</div>
					@endforeach
				</div>
			</div>
		</div>

		<div class="featured-product alt">
			<div class="container">
				<div class="row">
					<div class="col-md-5">
						<img src="/images/products/bagel2.png" />
					</div>
					<div class="col-md-7">
						<h2>Everybody's Favourite</h2>
						<h3>Egg &amp; Bacon</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae elit ac lacus facilisis accumsan. Proin et tellus auctor, dignissim libero ut, mattis enim. Donec mollis nulla imperdiet mauris lobortis posuere.</p>
						<a href="{{ route('product', ['product' => 'egg-and-bacon']) }}" class="btn btn-default">Read more</a>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
	{{-- <script type="text/javascript">
		var in_viewport = true,
			el = document.getElementById('restart-animation');;

		setTimeout(function() {
			el.style.animationPlayState = 'running';
		}, 2000);

		$(window).scroll(function() {
			if($('.logo-animation-sprite').isInViewport()) {
				if(!in_viewport) {
					restartAnimation();
				}

				in_viewport = true;
			} else {
				in_viewport = false;
			}
		});

		function restartAnimation()
		{
			el.style.animation = 'none';
			el.offsetHeight; /* trigger reflow to apply the change immediately */
			el.style.animation = null;
			el.style.animationPlayState = 'running';
		}

		$.fn.isInViewport = function()
		{
		    var elementTop = $(this).offset().top;
		    var elementBottom = elementTop + $(this).outerHeight();

		    var viewportTop = $(window).scrollTop();
		    var viewportBottom = viewportTop + $(window).height();

		    return elementBottom > viewportTop && elementTop < viewportBottom;
		};
	</script> --}}
@endsection

resources/views/homeredesign.blade.php
@extends('generic.chromelesslayout')

@section('content')
	<div class="page page-home-redesign">
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-9 offset-md-3">
						<ul>
							<li class="active"><a href="#">Home</a></li>
							<li><a href="#">Menu</a></li>
						</ul>
					</div>
				</div>
			</div>
		</header>

		<div class="header-hero">
			<div class="container">
				<img src="/images/logo-condensed.png" class="logo" />
				
				<div class="row">
					<div class="col-md-6">
						<h2>Delicious<span>Bagels</span></h2>
						<h3>Delivered to your door</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur fermentum ligula, non mollis nibh fringilla ornare.</p>

						<a href="#">Browse the Menu</a>
					</div>
					<div class="col-md-6">
						<img src="/images/products/bagel1.webp" class="img-fluid" />
					</div>
				</div>
			</div>
		</div>

		<div class="menu">
			<!-- <div class="container"> -->
				<smart-menu home="true"></smart-menu>
			<!-- </div> -->
		</div>

		<!-- <div class="deals">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<img src="/images/banners/mealdeal.jpg" class="img-fluid" />
						<img src="/images/banners/delivery.jpg" class="img-fluid" style="margin-top: 10px;" />
					</div>
					<div class="col-md-8">
						<img src="/images/banners/deliverycharge.jpg" class="img-fluid" style="margin-left: 10px;" />
					</div>
				</div>
			</div>
		</div> -->

		<modal-product></modal-product>
		<modal-product-info></modal-product-info>
	</div>
@endsection

resources/views/location.blade.php
@extends('generic.layout')

@section('content')
	<div class="page page-location">
		<div class="hero">
			<div class="caption">
				<h2>The Location</h2>
				<h3>Sit amet, consectetur adipiscing elit</h3>

				<input-location-search></input-location-search>
			</div>
		</div>

		<div id="map"></div>
	</div>
@endsection

@section('scripts')
	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7IfAc-GGtoSQH1imyUoRcAo8oRUxfZ0Q&callback=initMap"></script>
	<script type="text/javascript">
		function initMap()
		{
			var styledMapType = new google.maps.StyledMapType([
			    {
			        "featureType": "all",
			        "elementType": "labels.text.fill",
			        "stylers": [
			            {
			                "saturation": 36
			            },
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 40
			            }
			        ]
			    },
			    {
			        "featureType": "all",
			        "elementType": "labels.text.stroke",
			        "stylers": [
			            {
			                "visibility": "on"
			            },
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 16
			            }
			        ]
			    },
			    {
			        "featureType": "all",
			        "elementType": "labels.icon",
			        "stylers": [
			            {
			                "visibility": "off"
			            }
			        ]
			    },
			    {
			        "featureType": "administrative",
			        "elementType": "geometry.fill",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 20
			            }
			        ]
			    },
			    {
			        "featureType": "administrative",
			        "elementType": "geometry.stroke",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 17
			            },
			            {
			                "weight": 1.2
			            }
			        ]
			    },
			    {
			        "featureType": "landscape",
			        "elementType": "geometry",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 20
			            }
			        ]
			    },
			    {
			        "featureType": "poi",
			        "elementType": "geometry",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 21
			            }
			        ]
			    },
			    {
			        "featureType": "road.highway",
			        "elementType": "geometry.fill",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 17
			            }
			        ]
			    },
			    {
			        "featureType": "road.highway",
			        "elementType": "geometry.stroke",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 29
			            },
			            {
			                "weight": 0.2
			            }
			        ]
			    },
			    {
			        "featureType": "road.arterial",
			        "elementType": "geometry",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 18
			            }
			        ]
			    },
			    {
			        "featureType": "road.local",
			        "elementType": "geometry",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 16
			            }
			        ]
			    },
			    {
			        "featureType": "transit",
			        "elementType": "geometry",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 19
			            }
			        ]
			    },
			    {
			        "featureType": "water",
			        "elementType": "geometry",
			        "stylers": [
			            {
			                "color": "#000000"
			            },
			            {
			                "lightness": 17
			            }
			        ]
			    }
			]);

			var uluru = {lat: 51.5286416, lng: -0.1015987};
			var map = new google.maps.Map(document.getElementById('map'), {
				zoom: 12,
				center: uluru,
				disableDefaultUI: true,
			});

			map.mapTypes.set('styled_map', styledMapType);
			map.setMapTypeId('styled_map');

			var cityCircle = new google.maps.Circle({
		      	strokeColor: '#208bd3',
		      	strokeOpacity: 0.8,
		      	strokeWeight: 2,
		      	fillColor: '#208bd3',
		      	fillOpacity: 0.35,
		      	map: map,
		      	center: uluru,
		      	radius: (3.5 * 1609.34),
		    });
		}
	</script>
@endsection

resources/views/menu.blade.php
@extends('generic.newlayout')

@section('header')
	@include('generic.newheader', ['mini' => true, 'nopad' => true])
@endsection

@section('content')
	<div class="page page-menu">
        <div class="menu-content">
            <smart-menu @if($active) active="{{ $active }}"@endif></smart-menu>
        </div>
		<smart-cart></smart-cart>
	</div>

	<modal-product></modal-product>
	<modal-product-info></modal-product-info>
@endsection

resources/views/order.blade.php
@extends('generic.newlayout')

@section('header')
	@include('generic.newheader')
@endsection

@section('content')
	<div class="page page-account page-account-order page-account-order-new">
		<div class="content">
			<div class="container">
				<div class="detail-wrapper">
					<div class="order-details">
						<h2>
							New Order
							<small>Placed {{ $order->human_time }}</small>
							<span class="float-right">Delivering at <span>{{ $order->pretty_delivery_time }}</span></span>
						</h2>
						@foreach($order->lines as $item)
							@if($item->product)
								<div class="order-item">
									<div class="image">
										<img src="{{ $item->product->image_thumbnail }}" class="img-fluid" />
									</div>
									<div class="info">
										<h2>{{ $item->product->name }} @if($item->cheese)<span class="badge">with cheese</span>@endif</h2>
										<p><strong>Fillings:</strong> @if($item->filling_list){{ $item->filling_list }}@else None @endif</p>
										<p><strong>Sauces:</strong> @if($item->sauce_list){{ $item->sauce_list }}@else None @endif</p>
									</div>
									<div class="price">
										<h3>&pound;{{ $item->product->price }}</h3>
									</div>
								</div>
							@elseif($item->deal)
								<div class="order-item deal-item">
									<div class="image">
										<img src="{{ $item->deal->image_thumbnail }}" class="img-fluid" />
									</div>
									<div class="info">
										<h2>{{ $item->deal->name }}</h2>
										@foreach($item->deal_options as $option)
											<p>{{ $option->product->name }}</p>
										@endforeach
									</div>
									<div class="price">
										<h3>&pound;{{ $item->deal->price }}</h3>
									</div>
								</div>
							@endif
						@endforeach

						<div class="order-total">
							<h2 class="right">Total order cost <span>&pound;{{ $order->total_price }}</span></h2>
						</div>
					</div>

					<div class="payment-details">
						<header>
							<h2>Order details</h2>
							<p>Below are your payment details and any customer information relating to your order</p>
						</header>
						<div class="body">
							<div class="jp-card-container"><div class="jp-card jp-card-visa jp-card-identified"><div class="jp-card-front"><div class="jp-card-logo jp-card-elo"><div class="e">e</div><div class="l">l</div><div class="o">o</div></div><div class="jp-card-logo jp-card-visa">Visa</div><div class="jp-card-logo jp-card-visaelectron">Visa<div class="elec">Electron</div></div><div class="jp-card-logo jp-card-mastercard">Mastercard</div><div class="jp-card-logo jp-card-maestro">Maestro</div><div class="jp-card-logo jp-card-amex"></div><div class="jp-card-logo jp-card-discover">discover</div><div class="jp-card-logo jp-card-dinersclub"></div><div class="jp-card-logo jp-card-dankort"><div class="dk"><div class="d"></div><div class="k"></div></div></div><div class="jp-card-logo jp-card-jcb"><div class="j">J</div><div class="c">C</div><div class="b">B</div></div><div class="jp-card-lower"><div class="jp-card-shiny"></div><div class="jp-card-cvc jp-card-display jp-card-valid">111</div><div class="jp-card-number jp-card-display jp-card-valid">**** **** **** {{ $payment->charges->data[0]->payment_method_details->card->last4 }}</div><div class="jp-card-name jp-card-display jp-card-valid">J Emery</div><div class="jp-card-expiry jp-card-display jp-card-valid" data-before="month/year" data-after="validthru">{{ $payment->charges->data[0]->payment_method_details->card->exp_month }}/{{ $payment->charges->data[0]->payment_method_details->card->exp_year }}</div></div></div><div class="jp-card-back"><div class="jp-card-bar"></div><div class="jp-card-cvc jp-card-display jp-card-valid">***</div><div class="jp-card-shiny"></div></div></div></div>
						</div>
						<footer>
							<div class="address">
								<div class="row">
									<div class="col-md-6">
										<h2>Address</h2>
										<p>{{ $order->address->line1 }}</p>
										<p>{{ $order->address->line2 }}</p>
										<p>{{ $order->address->town }}</p>
										<p>{{ $order->address->postcode }}</p>
									</div>
									<div class="col-md-6">
										<h2 class="text-right">Delivery</h2>
										@if($order->guest)
											<p class="text-right">{{ $order->guest->name }}</p>
										@else
											<p class="text-right">{{ $order->user->name }}</p>
										@endif
										<p class="text-right">{{ $order->pretty_date }}</p>
										<p class="text-right">4:30pm</p>
									</div>
								</div>
							</div>
						</footer>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/soon.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="soon">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>BagelBaby - coming soon!</title>
        <link href="/css/app.css?v=1" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="coming-soon">
            <img src="/images/products/bagel1.webp" />
            <h2>BagelBaby</h2>
            <h3>Coming soon</h3>

            <img src="/images/logo-loop-fixed.gif" />
        </div>
        <script type="text/javascript" src="/js/app.js"></script>
    </body>
</html>